// @ts-check
import { defineConfig } from 'astro/config';
// https://astro.build/config
export default defineConfig({
  site: 'https://monroe-humane.org',
  output: 'static',
  redirects: {
    // Core alternate routes
    '/home': '/',
    '/volunteer': '/volunteer-form',
    '/adopt/apply': '/adoptions/#Application',
    '/adopt-form': '/adoptions/#Application',
    '/donate-now': '/donate',
    '/donations': '/donate',
    '/memorial': '/memorials',
    '/blank': '/dog-and-cat-shelter',
    '/petdisplay': '/adopt',
    '/empty-page': '/',
    '/adopt/species-cat': '/adopt/cats',
    '/adopt/species-dog': '/adopt/dogs',

    // 22-city SEO landing pages -> /adopt
    '/adoption-center': '/adopt',
    '/adoption-center/ash-township-mi': '/adopt',
    '/adoption-center/bedford-township-mi': '/adopt',
    '/adoption-center/dundee-mi': '/adopt',
    '/adoption-center/dundee-township-mi': '/adopt',
    '/adoption-center/erie-mi': '/adopt',
    '/adoption-center/exeter-mi': '/adopt',
    '/adoption-center/frenchtown-charter-mi': '/adopt',
    '/adoption-center/ida-mi': '/adopt',
    '/adoption-center/lasalle-mi': '/adopt',
    '/adoption-center/london-mi': '/adopt',
    '/adoption-center/luna-pier-mi': '/adopt',
    '/adoption-center/milan-township-mi': '/adopt',
    '/adoption-center/monroe-charter-mi': '/adopt',
    '/adoption-center/monroe-county-mi': '/adopt',
    '/adoption-center/raisinville-mi': '/adopt',
    '/adoption-center/summerfield-mi': '/adopt',
    '/adoption-center/temperance-mi': '/adopt',
    '/adoption-center/toledo-oh': '/adopt',
    '/adoption-center/wayne-county-mi': '/adopt',
    '/adoption-center/whiteford-mi': '/adopt',

    // 22-city SEO landing pages -> /adoptions
    '/animal-adoption': '/adoptions',
    '/animal-adoption/ash-township-mi': '/adoptions',
    '/animal-adoption/bedford-township-mi': '/adoptions',
    '/animal-adoption/dundee-mi': '/adoptions',
    '/animal-adoption/dundee-township-mi': '/adoptions',
    '/animal-adoption/erie-mi': '/adoptions',
    '/animal-adoption/exeter-mi': '/adoptions',
    '/animal-adoption/frenchtown-charter-mi': '/adoptions',
    '/animal-adoption/ida-mi': '/adoptions',
    '/animal-adoption/lasalle-mi': '/adoptions',
    '/animal-adoption/london-mi': '/adoptions',
    '/animal-adoption/luna-pier-mi': '/adoptions',
    '/animal-adoption/milan-township-mi': '/adoptions',
    '/animal-adoption/monroe-charter-mi': '/adoptions',
    '/animal-adoption/monroe-county-mi': '/adoptions',
    '/animal-adoption/raisinville-mi': '/adoptions',
    '/animal-adoption/summerfield-mi': '/adoptions',
    '/animal-adoption/temperance-mi': '/adoptions',
    '/animal-adoption/toledo-oh': '/adoptions',
    '/animal-adoption/wayne-county-mi': '/adoptions',
    '/animal-adoption/whiteford-mi': '/adoptions',

    // 22-city SEO landing pages -> /dog-and-cat-shelter
    '/animal-shelter': '/dog-and-cat-shelter',
    '/animal-shelter/ash-township-mi': '/dog-and-cat-shelter',
    '/animal-shelter/bedford-township-mi': '/dog-and-cat-shelter',
    '/animal-shelter/dundee-mi': '/dog-and-cat-shelter',
    '/animal-shelter/dundee-township-mi': '/dog-and-cat-shelter',
    '/animal-shelter/erie-mi': '/dog-and-cat-shelter',
    '/animal-shelter/exeter-mi': '/dog-and-cat-shelter',
    '/animal-shelter/frenchtown-charter-mi': '/dog-and-cat-shelter',
    '/animal-shelter/ida-mi': '/dog-and-cat-shelter',
    '/animal-shelter/lasalle-mi': '/dog-and-cat-shelter',
    '/animal-shelter/london-mi': '/dog-and-cat-shelter',
    '/animal-shelter/luna-pier-mi': '/dog-and-cat-shelter',
    '/animal-shelter/milan-township-mi': '/dog-and-cat-shelter',
    '/animal-shelter/monroe-charter-mi': '/dog-and-cat-shelter',
    '/animal-shelter/monroe-county-mi': '/dog-and-cat-shelter',
    '/animal-shelter/raisinville-mi': '/dog-and-cat-shelter',
    '/animal-shelter/summerfield-mi': '/dog-and-cat-shelter',
    '/animal-shelter/temperance-mi': '/dog-and-cat-shelter',
    '/animal-shelter/toledo-oh': '/dog-and-cat-shelter',
    '/animal-shelter/wayne-county-mi': '/dog-and-cat-shelter',
    '/animal-shelter/whiteford-mi': '/dog-and-cat-shelter',

    // Dog and cat shelter city variants
    '/dog-and-cat-shelter/ash-township-mi': '/dog-and-cat-shelter',
    '/dog-and-cat-shelter/bedford-township-mi': '/dog-and-cat-shelter',
    '/dog-and-cat-shelter/dundee-mi': '/dog-and-cat-shelter',
    '/dog-and-cat-shelter/dundee-township-mi': '/dog-and-cat-shelter',
    '/dog-and-cat-shelter/erie-mi': '/dog-and-cat-shelter',
    '/dog-and-cat-shelter/exeter-mi': '/dog-and-cat-shelter',
    '/dog-and-cat-shelter/frenchtown-charter-mi': '/dog-and-cat-shelter',
    '/dog-and-cat-shelter/ida-mi': '/dog-and-cat-shelter',
    '/dog-and-cat-shelter/lasalle-mi': '/dog-and-cat-shelter',
    '/dog-and-cat-shelter/london-mi': '/dog-and-cat-shelter',
    '/dog-and-cat-shelter/luna-pier-mi': '/dog-and-cat-shelter',
    '/dog-and-cat-shelter/milan-township-mi': '/dog-and-cat-shelter',
    '/dog-and-cat-shelter/monroe-charter-mi': '/dog-and-cat-shelter',
    '/dog-and-cat-shelter/monroe-county-mi': '/dog-and-cat-shelter',
    '/dog-and-cat-shelter/raisinville-mi': '/dog-and-cat-shelter',
    '/dog-and-cat-shelter/summerfield-mi': '/dog-and-cat-shelter',
    '/dog-and-cat-shelter/temperance-mi': '/dog-and-cat-shelter',
    '/dog-and-cat-shelter/toledo-oh': '/dog-and-cat-shelter',
    '/dog-and-cat-shelter/wayne-county-mi': '/dog-and-cat-shelter',
    '/dog-and-cat-shelter/whiteford-mi': '/dog-and-cat-shelter',

    // Hero fence city variants
    '/hero-fence': '/#hs-hero-fence-widget',
    '/hero-fence/ash-township-mi': '/#hs-hero-fence-widget',
    '/hero-fence/bedford-township-mi': '/#hs-hero-fence-widget',
    '/hero-fence/dundee-mi': '/#hs-hero-fence-widget',
    '/hero-fence/dundee-township-mi': '/#hs-hero-fence-widget',
    '/hero-fence/erie-mi': '/#hs-hero-fence-widget',
    '/hero-fence/exeter-mi': '/#hs-hero-fence-widget',
    '/hero-fence/frenchtown-charter-mi': '/#hs-hero-fence-widget',
    '/hero-fence/ida-mi': '/#hs-hero-fence-widget',
    '/hero-fence/lasalle-mi': '/#hs-hero-fence-widget',
    '/hero-fence/london-mi': '/#hs-hero-fence-widget',
    '/hero-fence/luna-pier-mi': '/#hs-hero-fence-widget',
    '/hero-fence/milan-township-mi': '/#hs-hero-fence-widget',
    '/hero-fence/monroe-charter-mi': '/#hs-hero-fence-widget',
    '/hero-fence/monroe-county-mi': '/#hs-hero-fence-widget',
    '/hero-fence/raisinville-mi': '/#hs-hero-fence-widget',
    '/hero-fence/summerfield-mi': '/#hs-hero-fence-widget',
    '/hero-fence/temperance-mi': '/#hs-hero-fence-widget',
    '/hero-fence/toledo-oh': '/#hs-hero-fence-widget',
    '/hero-fence/wayne-county-mi': '/#hs-hero-fence-widget',
    '/hero-fence/whiteford-mi': '/#hs-hero-fence-widget',

    // Resource legacy aliases
    '/pet-nail-trims-and-microchipping/monroe-county-mi': '/resources',
  },

  // Case-variant legacy URLs (WP links use /SpecialSponsors/). On
  // case-insensitive filesystems (Windows dev) these redirect keys collide
  // with the real page routes and shadow them, so register them only where
  // the filesystem is case-sensitive (Linux CI/production builds).
  ...(process.platform !== 'win32'
    ? { redirects: { '/SpecialSponsors': '/specialsponsors' } }
    : {}),
});
