// Shelter Run — tuning + asset manifest. Logical playfield is 432x768 (2:3 portrait).
export const VIEW = { W: 432, H: 768 };

// Pseudo-3D projection constants (Temple Run-style chase camera).
export const PROJ = {
  horizonRatio: 0.30,     // horizon line as fraction of view height
  focal: 400,
  cameraHeight: 190,
  playerZ: 200,           // fixed depth of the runner ahead of the camera
  laneWorldX: [-78, 0, 78],
  trackHalfW: 150,
  farZ: 2400,             // draw distance
  spawnZ: 2000,           // obstacles materialize just inside farZ
};

export const PHYS = {
  speedBase: 7.0,         // world units per 60fps frame
  speedMax: 23,
  speedGain: 0.0021,      // per frame
  distScale: 0.009,       // world units -> meters
  jumpHeight: 135,        // world units
  jumpMs: 580,
  slideMs: 520,
  laneChangeMs: 150,
  hitWindowFront: 120,    // depth window around playerZ for collisions
  hitWindowBack: 90,
  collectWindow: 75,
  lowWallHeight: 95,      // jump must clear this
  highBarBottom: 95,      // slide must be under this
  lives: 2,
  invincibleMs: 1600,
  chaseRecoverSec: 7.5,     // clean play needed for the kennel pack to drop back
  stumbleSpeedMul: 0.55,    // speed retained after a stumble
  magnetRadius: 1.6,        // lanes the magnet can pull from (adjacent)
  ghostSecPerLevel: 1.6,    // ghost-peek duration per upgrade level
  boostMetersPerLevel: 150, // boost distance per upgrade level (L1 ≈ 250m)
  donationValues: [0, 8, 16, 26, 40, 60], // mirrors server DONATION_VALUES (display only)
  treatTiers: [
    { minMeters: 0,    value: 1, tier: 'bronze' },
    { minMeters: 1500, value: 3, tier: 'silver' },
    { minMeters: 2800, value: 5, tier: 'gold'   },
  ],
  goldenThresholds: [       // Golden Treats upgrade shifts tier gates earlier
    [1500, 2800],           // L0
    [1300, 2400],           // L1
    [1100, 2000],           // L2
    [900,  1600],           // L3
    [700,  1200],           // L4
    [500,   800],           // L5
  ],
};

// Distance-gated biomes — palettes harmonized with flappy-cat-2's set.
export const BIOMES = [
  {
    min: 0, id: 'grass', label: 'Morning Meadow',
    sky: ['#63b8d8', '#cdeef0'], sun: '#fff3c4',
    trackA: '#8a6f4d', trackB: '#7d6444', edge: '#5fae67', lane: '#e8d9b0',
    sideA: '#4e9e58', sideB: '#45915150', sideStrip: '#57b065',
    fog: 'rgba(205,238,240,0.55)', particle: '#e8d9b0', collect: '#ffd166',
  },
  {
    min: 500, id: 'dirt', label: 'Golden Hour',
    sky: ['#e8975a', '#f8dca0'], sun: '#ffe9a8',
    trackA: '#9c7b52', trackB: '#8d6d47', edge: '#b58a4a', lane: '#f0d9a8',
    sideA: '#a8845a', sideB: '#97754c', sideStrip: '#bb9260',
    fog: 'rgba(248,220,160,0.5)', particle: '#ffd4a0', collect: '#ffe08a',
  },
  {
    min: 1400, id: 'snow', label: 'Dusk Frost',
    sky: ['#8d7fc9', '#e8d5f2'], sun: '#f4e8ff',
    trackA: '#b8c9d6', trackB: '#a7bccb', edge: '#8fb6d0', lane: '#eef5fa',
    sideA: '#cfe3ee', sideB: '#bcd5e4', sideStrip: '#dcebf4',
    fog: 'rgba(232,213,242,0.5)', particle: '#e0ecf4', collect: '#ffd166',
  },
  {
    min: 2600, id: 'ice', label: 'Starlight Run',
    sky: ['#182646', '#3d5a78'], sun: '#cfe4ff',
    trackA: '#5b7a94', trackB: '#4e6b84', edge: '#7fb0d8', lane: '#bfe0f4',
    sideA: '#3d5a78', sideB: '#324f6c', sideStrip: '#4a6a8c',
    fog: 'rgba(61,90,120,0.55)', particle: '#a0c0ff', collect: '#c0e0ff',
  },
];
export const BIOME_CYCLE_RESET = 4200; // meters; wraps back to grass

// Server REWARD_TABLE for game_id shelter_run — client only sends reward_key.
export const MILESTONES = [
  { key: 'distance_500',  at: 500,  label: 'Trail Blazer',   tier: 'standard' },
  { key: 'distance_1500', at: 1500, label: 'Rescue Ranger',  tier: 'standard' },
  { key: 'distance_3000', at: 3000, label: 'Marathon Meow',  tier: 'duo' },
];

export const MEDALS = [
  { min: 3000, img: 'ui/medalGold.png',   label: 'Gold' },
  { min: 1500, img: 'ui/medalSilver.png', label: 'Silver' },
  { min: 500,  img: 'ui/medalBronze.png', label: 'Bronze' },
];

// Rear-view (chase-cam) cat sheets: 1280x140 = 8 frames of 160x140.
// Frames 0-5 = run cycle, 6 = jump pose, 7 = slide pose. Generated by PIL.
export const CATS = [
  { id: 'calico', name: 'Calico',    sheet: 'catback_calico.png',  frames: 8, fw: 160, fh: 140 },
  { id: 'ginger', name: 'Marmalade', sheet: 'catback_ginger.png',  frames: 8, fw: 160, fh: 140 },
  { id: 'tuxedo', name: 'Tuxedo',    sheet: 'catback_tuxedo.png',  frames: 8, fw: 160, fh: 140 },
  { id: 'tabby',  name: 'Smokey',    sheet: 'catback_tabby.png',   frames: 8, fw: 160, fh: 140 },
];
export const MASCOT_TO_CAT = { smokey: 'tabby', marmalade: 'ginger' };
export const FRAME_RUN = [0, 1, 2, 3, 4, 5];
export const FRAME_JUMP = 6;
export const FRAME_SLIDE = 7;

export const IMAGES = {
  cats: CATS.map(c => c.sheet),
  decor: ['cloud1.png','cloud2.png','cloud3.png','cloud4.png','cloud5.png','cloud6.png',
          'house1.png','houseSmall1.png','tree.png','sun.png','star.png','puff.png'],
  rocks: ['rock.png', 'rockGrass.png', 'rockIce.png', 'rockSnow.png'],
  obstacles: ['obs_wall_0.png','obs_wall_1.png','obs_wall_2.png',
              'obs_low_0.png','obs_low_1.png','obs_low_2.png',
              'obs_high_0.png','obs_high_1.png','obs_high_2.png',
              'chase_dogs.png'],
  ui: ['ui/medalBronze.png','ui/medalGold.png','ui/medalSilver.png',
       'ui/tap.png','ui/textGameOver.png','ui/textGetReady.png'],
  numbers: Array.from({ length: 10 }, (_, i) => `numbers/number${i}.png`),
};

export const OBSTACLE = { LANE_BLOCK: 'lane_block', LOW: 'low', HIGH: 'high', GAP: 'gap' };

// Upgrade store — mirrors server UPGRADE_DEFS (server owns cost/level truth).
export const UPGRADES = {
  magnet:   { label: 'Treat Magnet',         icon: '🧲', costs: [60, 140, 280, 500, 800],   desc: 'Pulls pickups from nearby lanes. L5 triples treat value.' },
  golden:   { label: 'Golden Treats',        icon: '✨', costs: [50, 120, 250, 450, 700],   desc: 'Richer treats appear sooner on the trail.' },
  ghost:    { label: 'Ghost Pepper Zoomies', icon: '👻', costs: [80, 180, 360, 650, 1000],  desc: 'Phase straight through obstacles. Lasts longer per level.' },
  boost:    { label: 'Autopilot Sprint',     icon: '🚀', costs: [90, 200, 400, 700, 1100],  desc: 'Invincible full-speed sprint. Goes farther per level.' },
  donation: { label: 'Donation Burst',       icon: '💰', costs: [40, 100, 220, 400, 650],   desc: 'Instant coin donation when grabbed. More coins per level.' },
};

// Objectives — mirrors server OBJECTIVE_DEFS.shelter_run. Each claim = +1 multiplier.
export const OBJECTIVES = [
  { key: 'rescue_5',      label: 'Rescue 5 pets in one run' },
  { key: 'rescue_15',     label: 'Rescue 15 pets all-time' },
  { key: 'clean_1000',    label: 'Run 1000m without stumbling' },
  { key: 'streak_8',      label: 'Reach an 8-rescue streak' },
  { key: 'distance_750',  label: 'Run 750m in one run' },
  { key: 'distance_2500', label: 'Run 2500m in one run' },
  { key: 'nearmiss_3',    label: 'Dodge 3 obstacles by a whisker in one run' },
  { key: 'pickups_2',     label: 'Grab 2 power-ups in one run' },
  { key: 'runs_5',        label: 'Finish 5 runs' },
  { key: 'chase_escape',  label: 'Escape the kennel pack' },
];

// World power-up pickups (spawn only when the matching upgrade is owned)
// plus the always-spawning treat.
export const PICKUP = { TREAT: 'treat', MAGNET: 'magnet', GHOST: 'ghost', BOOST: 'boost', DONATION: 'donation' };
export const PICKUP_STYLE = {
  treat:    { color: '#ffb347', glyph: '🦴' },
  magnet:   { color: '#ff8fa3', glyph: '🧲' },
  ghost:    { color: '#cdb4f0', glyph: '👻' },
  boost:    { color: '#ffd166', glyph: '🚀' },
  donation: { color: '#7ee0a3', glyph: '💰' },
};

export const SAVE_SLOT = 'default';
export const SCHEMA_VERSION = 1;
export const GAME_ID = 'shelter_run';
